### PR TITLE
fix deprecated  impls, closes #72

### LINKED ISSUE #72: hcl resume warning: respond_to is old fashion which takes only one parameter
Calling `hcl resume` spits out a bunch of warnings to the screen. Running ruby 2.3 and hcl 0.4.15:

```
/usr/local/lib/ruby/gems/2.3.0/gems/hcl-0.4.15/lib/hcl/task.rb:8: warning: HCl::Task#respond_to?(:to_ary) is old fashion which takes only one parameter
/usr/local/lib/ruby/gems/2.3.0/gems/hcl-0.4.15/lib/hcl/timesheet_resource.rb:15: warning: respond_to? is defined here
/usr/local/lib/ruby/gems/2.3.0/gems/hcl-0.4.15/lib/hcl/app.rb:54: warning: HCl::DayEntry#respond_to?(:to_ary) is old fashion which takes only one parameter
/usr/local/lib/ruby/gems/2.3.0/gems/hcl-0.4.15/lib/hcl/timesheet_resource.rb:15: warning: respond_to? is defined here
```

### PR DESCRIPTION
**Pull request by charneykaye**
See https://github.com/zenhob/hcl/issues/72

Thanks for hcl!

### CODE REVIEW

**Comment by zenhob** [comment]
This is very helpful, thank you! Would you be willing to resubmit this without the version bump?

**Comment by charneykaye** [comment]
There you go @zenhob thanks!

File: lib/hcl/version.rb [hunk 1]
```diff
@@ -1,3 +1,3 @@
 module HCl
-  VERSION = '0.4.15'
```
Comment (zenhob) [inline lib/hcl/version.rb]: I'd prefer the version bump to be in a separate commit, could you remove this change from the patch?

File: Gemfile.lock [hunk 2]
```diff
@@ -1,7 +1,7 @@
 PATH
   remote: .
   specs:
-    hcl (0.4.15)
+    hcl (0.4.16)
```
Comment (zenhob) [inline Gemfile.lock]: We should keep the exiting version for this too.

**Comment by zenhob** [comment]
Sorry, I meant the hcl version bumps in the `version.rb` and `Gemfile.lock`. I will be releasing a new version of HCl with your fixes, but I want to add the version bump in a separate commit. If you could remove those bits from the patch I'd appreciate it.

Again, thank you so much!

**Comment by charneykaye** [comment]
@zenhob thanks for the guidance here. I think this last push is the right stuff.
